ecommerce_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: XAXKNSR-HW11441
      user: AYUSHFULSUNDAR24
      password: Ayushful@123456
      role: ACCOUNTADMIN
      database: ECOMMERCE_DB
      warehouse: COMPUTE_WH
      schema: analytics
      threads: 1
      client_session_keep_alive: false
